=== Khedoth/enssat/XML-bibliotheque/biblio.dtd
<!ELEMENT biblio (livres, categories, emprunts)*>

<!ELEMENT livres (livre+)>
<!ELEMENT livre (titre,auteur,editeur,ref)>
<!ATTLIST livre cat IDREF #REQUIRED>
<!ATTLIST livre lieu NMTOKEN #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT ref (#PCDATA)>

<!ELEMENT categories (categorie)*>
<!ELEMENT categorie EMPTY>
<!ATTLIST categorie code ID #REQUIRED>
<!ATTLIST categorie desc NMTOKEN #REQUIRED>

<!ELEMENT emprunts (emprunt)*>
<!ELEMENT emprunt (refLivre, emprunteur, dateEmprunt, dateRetour)>
<!ELEMENT refLivre (#PCDATA)>
<!ELEMENT emprunteur (#PCDATA)>
<!ELEMENT dateEmprunt (#PCDATA)>
<!ELEMENT dateRetour (#PCDATA)>

=== Khedoth/enssat/XML-bibliotheque/ma_biblio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BookList SYSTEM "biblio.dtd">

<biblio>
	<livres>
		<livre cat="F" lieu="biblio1">
			<titre>Un balcon en forêt</titre>
			<auteur>Julien Gracq</auteur>
			<editeur>José Corti</editeur>
			<ref>978-2-7143-0333-2</ref>
		</livre>
		<livre cat="F" lieu="biblio2">
			<titre>Savages</titre>
			<auteur>Lew Wallace</auteur>
			<editeur>Reader's Digest</editeur>
			<ref>70-049-1</ref>
		</livre>
		<livre cat="D" lieu="biblio1">
			<titre>Macbeth</titre>
			<auteur>William Shakespeare</auteur>
			<editeur>Flammarion</editeur>
			<ref>978-2-0812-3156-6</ref>
		</livre>
		<livre cat="F" lieu="biblio2">
			<titre>Tales of Grandpa Cat</titre>
			<auteur>Wardlaw, Lee, Smith, John</auteur>
			<editeur>Associated Press</editeur>
			<ref>id1238</ref>
		</livre>
		<livre cat="C" lieu="biblio2">
			<titre>Learn Java Now</titre>
			<auteur>Stephen R. Davis</auteur>
			<editeur>Microsoft Corporation</editeur>
			<ref>id2341</ref>
		</livre>
		<livre cat="S" lieu="biblio2">
			<titre>Number, the Language of Science</titre>
			<auteur>Danzig</auteur>
			<editeur></editeur>
			<ref>id1234</ref>
		</livre>
	</livres>
	<categories>
		<categorie code="S" desc="Science"/>
		<categorie code="C" desc="Computing"/>
		<categorie code="X" desc="Crime"/>
		<categorie code="F" desc="Fiction"/>
		<categorie code="D" desc="Drama"/>
	</categories>
	<emprunts>
		<emprunt>
			<refLivre>978-2-7143-0333-2</refLivre>
			<emprunteur>A010</emprunteur>
			<dateEmprunt>10-10-2013</dateEmprunt>
			<dateRetour>20-10-2013</dateRetour>
		</emprunt>
		<emprunt>
			<refLivre>978-2-7143-0333-2</refLivre>
			<emprunteur>A042</emprunteur>
			<dateEmprunt>05-11-2013</dateEmprunt>
			<dateRetour></dateRetour>
		</emprunt>
		<emprunt>
			<refLivre>978-2-0812-3156-6</refLivre>
			<emprunteur>A042</emprunteur>
			<dateEmprunt>25-10-2013</dateEmprunt>
			<dateRetour>05-11-2013</dateRetour>
		</emprunt>
		<emprunt>
			<refLivre>id1238</refLivre>
			<emprunteur>A036</emprunteur>
			<dateEmprunt>12/02/2013</dateEmprunt>
			<dateRetour>12/03/2013</dateRetour>
		</emprunt>
		<emprunt>
			<refLivre>id2341</refLivre>
			<emprunteur>A010</emprunteur>
			<dateEmprunt>1/02/2013</dateEmprunt>
			<dateRetour>10/03/2013</dateRetour>
		</emprunt>
		<emprunt>
			<refLivre>id2341</refLivre>
			<emprunteur>A121</emprunteur>
			<dateEmprunt>15/03/2013</dateEmprunt>
			<dateRetour>08/03/2013</dateRetour>
		</emprunt>
	</emprunts>
</biblio>
